# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket                      = "hnt-metaverse-uat-tfstate-888577046292"
    dynamodb_table              = "hnt-metaverse-uat-terraform-locks"
    encrypt                     = true
    key                         = "./terraform.tfstate"
    region                      = "ap-northeast-1"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
  }
}
